### ISSUE TITLE
Development Checklist

### ISSUE THREAD

**Issue by gogabrielbr** [BarakChamo/ToysThatMakeNoise#1]
DEVELOPMENT CHECKLIST:

- Project Outline
- Reference and Pre Production 
- Development
- Documentation
- Presentation

**Pre Production**

- list ideas, functions, actions and necessary object
- Install SDKS, correct Unity versions, Addons and Packages
-

**Development**

- [x] VUFORIA prototype

- [ ] HOLOLENS prototype

- [ ] VUFORIA/HOLOLENS interface

- [ ] Assets development - Sound and Objects

- [ ] Spatial Sound Deployment

- [ ] Spatial Sound/Vuforia/HoloLens Interface
